/**
 * esbuild config for Node.js SEA (Single Executable Application)
 * Produces an ESM bundle, then wraps it as a self-executing CJS script for SEA.
 *
 * Reads sea-config.json (generated by scripts/generate_sea_assets.js) to embed
 * asset keys into the SEA preamble for runtime extraction.
 */

import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import {
  readFileSync,
  writeFileSync,
  rmSync,
  mkdirSync,
  existsSync,
} from 'node:fs';

let esbuild;
try {
  esbuild = (await import('esbuild')).default;
} catch (_error) {
  console.warn('esbuild not available, skipping SEA bundle step');
  process.exit(0);
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const require = createRequire(import.meta.url);
const pkg = require(path.resolve(__dirname, 'package.json'));

const seaDistDir = path.resolve(__dirname, 'dist-sea');

// Ensure dist-sea directory exists (don't delete — assets may already be there)
mkdirSync(seaDistDir, { recursive: true });
// Clean only bundle artifacts, not assets
for (const f of ['cli.mjs', 'cli.cjs', 'sea-prep.blob']) {
  rmSync(path.join(seaDistDir, f), { force: true });
}

// Read asset keys from sea-config.json (generated by generate_sea_assets.js)
const seaConfigPath = path.resolve(__dirname, 'sea-config.json');
let assetKeys = [];
if (existsSync(seaConfigPath)) {
  const seaConfig = JSON.parse(readFileSync(seaConfigPath, 'utf8'));
  assetKeys = seaConfig.assets ? Object.keys(seaConfig.assets) : [];
}

const external = [
  '@lydell/node-pty',
  'node-pty',
  '@lydell/node-pty-darwin-arm64',
  '@lydell/node-pty-darwin-x64',
  '@lydell/node-pty-linux-x64',
  '@lydell/node-pty-win32-arm64',
  '@lydell/node-pty-win32-x64',
  '@teddyzhu/clipboard',
  '@teddyzhu/clipboard-darwin-arm64',
  '@teddyzhu/clipboard-darwin-x64',
  '@teddyzhu/clipboard-linux-x64-gnu',
  '@teddyzhu/clipboard-linux-arm64-gnu',
  '@teddyzhu/clipboard-win32-x64-msvc',
  '@teddyzhu/clipboard-win32-arm64-msvc',
];

// Step 1: Build ESM bundle (supports top-level await from ink/yoga-layout)
await esbuild.build({
  entryPoints: ['packages/cli/index.ts'],
  bundle: true,
  outfile: 'dist-sea/cli.mjs',
  platform: 'node',
  format: 'esm',
  target: 'node20',
  external,
  packages: 'bundle',
  inject: [path.resolve(__dirname, 'scripts/esbuild-shims.js')],
  alias: {
    'is-in-ci': path.resolve(__dirname, 'packages/cli/src/patches/is-in-ci.ts'),
  },
  define: {
    'process.env.CLI_VERSION': JSON.stringify(pkg.version),
    global: 'globalThis',
  },
  loader: { '.node': 'file' },
  metafile: true,
  write: true,
  keepNames: true,
});

// Step 2: Wrap the ESM bundle into a CJS-compatible script for SEA
// SEA evaluates scripts as CJS, so we wrap in an async IIFE and
// replace ESM-only constructs.
let esmCode = readFileSync('dist-sea/cli.mjs', 'utf8');

// Remove shebang (not needed in SEA)
esmCode = esmCode.replace(/^#!.*\n/, '');

// Replace all import.meta.url with CJS equivalent
// In SEA mode with embedded assets, __SEA_ASSETS_DIR points to the temp
// extraction directory.  Falling back to process.execPath for non-SEA usage.
const importMetaUrlReplacement =
  '(globalThis.__SEA_ASSETS_DIR' +
  ' ? require("url").pathToFileURL(require("path").join(globalThis.__SEA_ASSETS_DIR, "cli.cjs")).href' +
  ' : require("url").pathToFileURL(process.execPath).href)';

esmCode = esmCode.replace(/\bimport\.meta\.url\b/g, importMetaUrlReplacement);

esmCode = esmCode.replace(
  /\bimport\.meta\.dirname\b/g,
  '(globalThis.__SEA_ASSETS_DIR || __dirname)',
);
esmCode = esmCode.replace(
  /\bimport\.meta\.filename\b/g,
  '(globalThis.__SEA_ASSETS_DIR ? require("path").join(globalThis.__SEA_ASSETS_DIR, "cli.cjs") : __filename)',
);

// Convert ALL top-level ESM imports to CJS requires
// Match both "node:xxx" prefixed and bare Node.js builtin modules
const modPattern = '[^"]+'; // Match any module specifier

// Pattern: import X from "xxx";
esmCode = esmCode.replace(
  new RegExp(`^import\\s+(\\w+)\\s+from\\s+"(${modPattern})";$`, 'gm'),
  'const $1 = require("$2");',
);
// Pattern: import { X, Y as Z } from "xxx";
esmCode = esmCode.replace(
  new RegExp(`^import\\s+\\{([^}]+)\\}\\s+from\\s+"(${modPattern})";$`, 'gm'),
  (_, imports, mod) => {
    const fixed = imports.replace(/\b(\w+)\s+as\s+(\w+)\b/g, '$1: $2');
    return `const {${fixed}} = require("${mod}");`;
  },
);
// Pattern: import * as X from "xxx";
esmCode = esmCode.replace(
  new RegExp(
    `^import\\s+\\*\\s+as\\s+(\\w+)\\s+from\\s+"(${modPattern})";$`,
    'gm',
  ),
  'const $1 = require("$2");',
);
// Pattern: import X, { Y as Z } from "xxx";
esmCode = esmCode.replace(
  new RegExp(
    `^import\\s+(\\w+),\\s*\\{([^}]+)\\}\\s+from\\s+"(${modPattern})";$`,
    'gm',
  ),
  (_, def, imports, mod) => {
    const fixed = imports.replace(/\b(\w+)\s+as\s+(\w+)\b/g, '$1: $2');
    return `const ${def} = require("${mod}"); const {${fixed}} = ${def};`;
  },
);

// SEA preamble: TTY fix, relaunch skip, and embedded asset extraction
const seaPreamble = `
// --- SEA Preamble ---
(function() {
  // 0. Suppress the harmless "require() in SEA only supports built-in modules" warning.
  //    Our preamble only requires built-ins (node:sea, os, fs, path, crypto), so this is safe.
  var _origEmit = process.emit;
  process.emit = function(evt) {
    if (evt === 'warning' && arguments[1] && arguments[1].message &&
        arguments[1].message.indexOf('single-executable') !== -1) {
      return false;
    }
    return _origEmit.apply(this, arguments);
  };

  // 1. On Windows SEA, process.stdin.isTTY is undefined even in a real terminal.
  //    Use process.stdout.isTTY as a proxy: if stdout is a TTY, stdin likely is too.
  if (process.platform === 'win32' && typeof process.stdin.isTTY === 'undefined' && process.stdout.isTTY) {
    Object.defineProperty(process.stdin, 'isTTY', { value: true, writable: true, configurable: true });
  }

  // 2. The relaunch logic assumes process.argv[1] is a script file, but SEA
  //    has no script entry in argv.  Skip relaunch to avoid a broken child spawn.
  process.env['MOLI_CODE_NO_RELAUNCH'] = 'true';

  // 3. Extract embedded assets to a temp directory so all path resolution works.
  var _sea;
  try { _sea = require('node:sea'); } catch(_e) {}
  if (_sea && typeof _sea.isSea === 'function' && _sea.isSea()) {
    var _os = require('os');
    var _fs = require('fs');
    var _path = require('path');
    var _crypto = require('crypto');

    // Stable temp dir based on exe path + mtime — invalidates when exe is rebuilt
    var _exeMtime = _fs.statSync(process.execPath).mtimeMs.toString();
    var _exeHash = _crypto.createHash('md5').update(process.execPath + '\\n' + _exeMtime).digest('hex').slice(0, 8);
    var _tempBase = _path.join(_os.tmpdir(), 'moli-code-sea-' + _exeHash);

    var _assetKeys = ${JSON.stringify(assetKeys)};

    // Only extract if sentinel is missing (first run or exe was rebuilt)
    var _sentinel = _path.join(_tempBase, '.sea-extracted');
    if (!_fs.existsSync(_sentinel)) {
      _fs.mkdirSync(_tempBase, { recursive: true });
      for (var _i = 0; _i < _assetKeys.length; _i++) {
        var _key = _assetKeys[_i];
        var _dest = _path.join(_tempBase, _key);
        _fs.mkdirSync(_path.dirname(_dest), { recursive: true });
        _fs.writeFileSync(_dest, new Uint8Array(_sea.getRawAsset(_key)));
      }
      _fs.writeFileSync(_sentinel, Date.now().toString());
    }

    globalThis.__SEA_ASSETS_DIR = _tempBase;
  }
})();
// --- End SEA Preamble ---
`;

// Wrap the entire code in an async IIFE to support top-level await
const wrappedCode = `// Node.js SEA bundle for moli-code
"use strict";
${seaPreamble}
(async () => {
${esmCode}
})().catch(err => { console.error(err); process.exit(1); });
`;

writeFileSync('dist-sea/cli.cjs', wrappedCode);

// Clean up intermediate ESM file
rmSync('dist-sea/cli.mjs');

const sizeBytes = Buffer.byteLength(wrappedCode);
console.log(
  `SEA bundle created: dist-sea/cli.cjs (${(sizeBytes / 1024 / 1024).toFixed(1)}MB)`,
);
if (assetKeys.length > 0) {
  console.log(`  Embedded ${assetKeys.length} asset keys in preamble`);
}
